CREATE TABLE topicos(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL UNIQUE,
    autor VARCHAR(255) NOT NULL UNIQUE,
    mensagem TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT 1,
    data_criacao DATETIME NOT NULL,
    curso VARCHAR(255) NOT NULL
);
